repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v3.2.0
  hooks:
    - id: check-byte-order-marker
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: git://github.com/antonbabenko/pre-commit-terraform.git
  sha: v1.43.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.10
  hooks:
    - id: shellcheck
    - id: gofmt
